import { Router } from 'express';
import { confirmOrder, createOrder, listOrders, rejectOrder, updateOrderStatus } from '../controllers/orderController.js';
import { adminOnly, protect } from '../middleware/auth.js';
const router = Router();
router.use(protect);
router.get('/', listOrders);
router.post('/', createOrder);
router.patch('/:id/status', adminOnly, updateOrderStatus);
router.post('/:id/confirm', adminOnly, confirmOrder);
router.post('/:id/reject', adminOnly, rejectOrder);
export default router;
